
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(EMPNO NUMERIC(4) NOT NULL,
ENAME VARCHAR(10),
JOB VARCHAR(9),
MGR NUMERIC(4),
HIREDATE DATETIME,
SAL NUMERIC(7, 2),
COMM NUMERIC(7, 2),
DEPTNO NUMERIC(2))

INSERT INTO EMP VALUES
(7369, 'SMITH', 'CLERK', 7902, '17-DEC-1980', 800, NULL, 20)
INSERT INTO EMP VALUES
(7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-1981', 1600, 300, 30)
INSERT INTO EMP VALUES
(7521, 'WARD', 'SALESMAN', 7698, '22-FEB-1981', 1250, 500, 30)
INSERT INTO EMP VALUES
(7566, 'JONES', 'MANAGER', 7839, '2-APR-1981', 2975, NULL, 20)
INSERT INTO EMP VALUES
(7654, 'MARTIN', 'SALESMAN', 7698, '28-SEP-1981', 1250, 1400, 30)
INSERT INTO EMP VALUES
(7698, 'BLAKE', 'MANAGER', 7839, '1-MAY-1981', 2850, NULL, 30)
INSERT INTO EMP VALUES
(7782, 'CLARK', 'MANAGER', 7839, '9-JUN-1981', 2450, NULL, 10)
INSERT INTO EMP VALUES
(7788, 'SCOTT', 'ANALYST', 7566, '09-DEC-1982', 3000, NULL, 20)
INSERT INTO EMP VALUES
(7839, 'KING', 'PRESIDENT', NULL, '17-NOV-1981', 5000, NULL, 10)
INSERT INTO EMP VALUES
(7844, 'TURNER', 'SALESMAN', 7698, '8-SEP-1981', 1500, 0, 30)
INSERT INTO EMP VALUES
(7876, 'ADAMS', 'CLERK', 7788, '12-JAN-1983', 1100, NULL, 20)
INSERT INTO EMP VALUES
(7900, 'JAMES', 'CLERK', 7698, '3-DEC-1981', 950, NULL, 30)
INSERT INTO EMP VALUES
(7902, 'FORD', 'ANALYST', 7566, '3-DEC-1981', 3000, NULL, 20)
INSERT INTO EMP VALUES
(7934, 'MILLER', 'CLERK', 7782, '23-JAN-1982', 1300, NULL, 10)

DROP TABLE IF EXISTS DEPT
CREATE TABLE DEPT
(DEPTNO NUMERIC(2),
DNAME VARCHAR(14),
LOC VARCHAR(13) )

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK')
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS')
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO')
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON')
-------------------------------------------------------------
--UPDATE EMP SET DEPTNO=30 WHERE EMPNO=7934

SELECT * FROM EMP Order by DEPTNO
SELECT * FROM DEPT


SELECT Loc, COUNT(*)
FROM Dept d
INNER JOIN Emp e
ON d.DEPTNO=e.DEPTNO
GROUP BY Loc


SELECT  *
FROM Dept d
LEFT JOIN Emp e
ON d.DEPTNO=e.DEPTNO



SELECT Loc, COUNT(*) Emp_cnt
FROM Dept d
LEFT JOIN Emp e
ON d.DEPTNO=e.DEPTNO
WHERE e.DEPTNO IS NOT NULL
GROUP BY Loc
ORDER BY Emp_cnt


SELECT  d.DEPTNO, D.DNAME
FROM Dept d
LEFT JOIN Emp e
ON d.DEPTNO = e.DEPTNO
WHERE e.DEPTNO IS NULL


SELECT TOP 1  d.DEPTNO,d.DNAME, COUNT(*) cnt
FROM dept d
INNER JOIN emp e
ON d.DEPTNO=e.DEPTNO
GROUP BY d.DEPTNO,d.DNAME
ORDER BY cnt DESC

SELECT TOP 2  d.DEPTNO,d.DNAME, SUM(SAL) Salary
FROM dept d
INNER JOIN emp e
ON d.DEPTNO=e.DEPTNO
GROUP BY d.DEPTNO,d.DNAME
ORDER BY Salary DESC

-- Can I give 20 records though I have 3 records in result set: Yes, you can give
-- INNER JOIN

SELECT Empno,ENAME,dept.DEPTNO,Dname
FROM Emp 
INNER JOIN Dept ON emp.deptno=dept.deptno 

-- LEFT JOIN

SELECT Empno,ENAME,e.DEPTNO,Dname,Loc
FROM Emp e
LEFT JOIN Dept d ON e.deptno=d.deptno

SELECT e.DEPTNO,Dname, COUNT(*) AS Number_of_Employees
FROM Emp e
LEFT JOIN Dept d ON e.deptno=d.deptno
GROUP BY e.DEPTNO,Dname
Order by 3 DESC


-- Right JOIN
SELECT Empno,ENAME,e.DEPTNO,Dname,Loc
FROM Emp e
RIGHT JOIN Dept d ON e.deptno=d.deptno

SELECT Empno,ENAME,e.DEPTNO,Dname,Loc
FROM dept e
LEFT JOIN Emp d ON e.deptno=d.deptno

-- Full Outer

SELECT Empno,ENAME,e.DEPTNO,Dname,Loc
FROM EMP e
FULL OUTER JOIN Dept d ON e.deptno=d.deptno

-- CROSS JOIN 
SELECT Empno,ENAME,e.DEPTNO,Dname,Loc
FROM EMP e
CROSS JOIN Dept d 

